name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack

### Set your workflow to run on push events to the main and release/* branches

on:
  push:
  branches:
    - main
    - release/*
   
### Set your workflow to run on pull_request events that target the main branch

  on:
  pull_request:
    branches:
    - main
    
  ### Set your workflow to run every day of the week from Monday to Friday at 2:00 UTC

on:
  schedule:
  - cron: "0 2 * * 1-5"
  
  
  ### in .github/workflows/webpack.yml 

  
  ### Manually running a workflow
  
on:
  workflow_dispatch:
  
  ### Running your jobs on different operating systems

To set the operating system for your job, specify the operating system using runs-on:

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    

### Using an action/ .github/workflows/webpack.yml

- name: Setup Node
  uses: actions/setup-node@v1
  with:
    node-version: '10.x'
    
    
### Running a command

- name: Install Dependencies
  run: npm install
  

### Running a job across a matrix of operating systems and runtime versions

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test


### Running steps or jobs conditionally

steps:
- run: npm publish
  if: github.event_name == 'push'
  
